plugins {
    id 'com.gradleup.shadow' version "${shadow_version}" apply false
    id 'de.maxhenkel.cursegradle' version "${cursegradle_version}" apply false
    id 'com.modrinth.minotaur' version "${minotaur_version}" apply false
    id 'mod-update' version "${mod_update_version}" apply false
    id 'fabric-loom' version "${fabric_loom_version}" apply false
}

apply from: "https://raw.githubusercontent.com/henkelmax/mod-gradle-scripts/${mod_gradle_script_version}/taskutils.gradle"

tasks.register('01-publishForge') {
    group = 'voicechat'
    doLast {
        runGradleTasks(['common:clean', 'common-client:clean', 'forge:clean'], ['forge:curseforge', 'forge:modrinth', 'forge:modUpdate'])
    }
}

tasks.register('02-publishFabric') {
    group = 'voicechat'
    doLast {
        runGradleTasks(['common:clean', 'common-client:clean', 'fabric:clean', 'fabric:api-stub:clean'], ['fabric:curseforge', 'fabric:modrinth', 'fabric:modUpdate'])
    }
}