org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

java_version=8
java_toolchain_version=8
voicechat_compatibility_version=20

minecraft_version=1.12.2

forge_version=14.23.5.2860

# Dependencies
configbuilder_version=2.1.0
concentus_version=1.0.1
opus4j_version=2.1.3
rnnoise4j_version=2.1.3
lame4j_version=2.1.5
speex4j_version=1.0.3

# Mod information
mod_version=1.12.2-2.6.11
mod_compatible_version=2.6.x
mod_id=voicechat
mod_display_name=Simple Voice Chat

forge_mappings_channel=snapshot
forge_mappings_version=20171003-1.12

# Script configuration
enable_configbuilder=true
include_mixins=false

# Project upload
curseforge_upload_id=416089
modrinth_upload_id=9eGKb6K1
hangar_upload_id=SimpleVoiceChat
curseforge_bukkit_upload_id=498303
modrinth_upload_include_prefix=false
upload_release_type=release
upload_recommended=true

# Gradle plugins
mod_gradle_script_version=1.0.54
forgegradle_version=[6.0.16,6.2)
mod_update_version=2.0.0
cursegradle_version=1.5.1
shadow_version=8.3.6
minotaur_version=2.+
mixingradle_version=0.7-SNAPSHOT
maven_settings_version=0.5
