org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_loader=quilt

minecraft_dependency=1.21.8
quilt_loader_version=0.30.1-beta.2
quilt_loader_dependency=>=0.30.0

fabric_api_version=0.129.0+1.21.8
fabric_api_dependency_breaks=<0.129.0+1.21.8

included_fabric_api_modules=\
  fabric-api-base, \
  fabric-command-api-v2, \
  fabric-lifecycle-events-v1, \
  fabric-networking-api-v1, \
  fabric-resource-loader-v0, \
  fabric-key-binding-api-v1

# Dependencies
modmenu_version=15.0.0
fabric_permission_api_version=0.3.3
viaversion_version=5.0.0
vanish_version=1.5.20+1.21.7

# Optional dependencies
curseforge_upload_optional_dependencies=modmenu, sound-physics-remastered, cloth-config, \
  audioplayer, luckperms, viafabric, meliusvanish
modrinth_upload_optional_dependencies=modmenu, sound-physics-remastered, cloth-config, \
  audioplayer, luckperms, viafabric, vanish
