mod_loader=forge

included_projects=:api, :common, :common-client

minecraft_dependency=[26.3, 26.4)

forge_version=66.0.0
forge_dependency=[66.0.0,)

include_mixins=true
use_mixins=true

# Optional dependencies
curseforge_upload_optional_dependencies=sound-physics-remastered, cloth-config
modrinth_upload_optional_dependencies=sound-physics-remastered, cloth-config
