mod_loader=forge

included_projects=:api, :common, :common-client

forge_version=54.1.5
forge_dependency=[54.1.5,)

reobfuscate=false

# Optional dependencies
curseforge_upload_optional_dependencies=sound-physics-remastered, cloth-config
modrinth_upload_optional_dependencies=sound-physics-remastered, cloth-config
