mod_loader=neoforge

included_projects=:api, :common, :common-client

neoforge_version=26.1.0.0-alpha.15+pre-3
neoforge_dependency=[26.1.0.0-alpha,)

# Optional dependencies
curseforge_upload_optional_dependencies=simple-voice-chat, cloth-config
modrinth_upload_optional_dependencies=simple-voice-chat, cloth-config
