mod_loader=paper

included_projects=:api, :common

paper_version=26.1.1.build.+

enable_hangar_upload=true
enable_curseforge_upload=false
enable_mod_update=false

upload_release_type=alpha
upload_recommended=true

placeholder_api_version=2.12.2
viaversion_version=5.8.1

# TODO purpur, folia
modrinth_upload_supported_loaders=paper

hangar_upload_dependencies=ViaVersion, ViaBackwards
hangar_upload_minecraft_versions=26.1.1
